{{- if .Values.plugin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-plugin-test
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: container-0
          stdin: true
          tty: true
{{- end }}